name: Docker Build

on:
  pull_request: { }

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: php

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
